### ISSUE TITLE
Model import

### ISSUE THREAD

**Issue by JefferyDaHu** [KIT-ISAS/iviz#13]
Thank you for your great work. I am trying to import my own robot model to Unity. However, the model failed to be imported with errors. My computer is running win10 and I create a ros_package_path file at c:/users/account/.iviz/ros_package_path. I also enable model service in the setting. 

![image](https://user-images.githubusercontent.com/29313094/120357351-597a3000-c2d3-11eb-9236-ea266eb74d36.png)

**Comment by akzeac** [comment]
Hi, that's a weird error. Usually the error is that the service cannot find the file, but in your case iviz cannot find its own service.
Do you have a ROS installation and can you do rosservice list? Does /iviz/get_model_resource appear there?

**Comment by JefferyDaHu** [comment]
> Hi, that's a weird error. Usually the error is that the service cannot find the file, but in your case iviz cannot find its own service.
> Do you have a ROS installation and can you do rosservice list? Does /iviz/get_model_resource appear there?

**Comment by JefferyDaHu** [comment]
Thank you for your quick response. I have attached the message of rosservice list on Ubuntu 16 for jackal robot. 
![image](https://user-images.githubusercontent.com/29313094/120658711-48542f00-c44b-11eb-892f-cea00715c435.png)
This is the ros_package_path on my windows computer running iviz. 
![image](https://user-images.githubusercontent.com/29313094/120658948-83eef900-c44b-11eb-9312-600178deced1.png)
I tried to run with the turtlebot robot in the gazebo. I got another error message. The sensor data can be correctly visualized.
![image](https://user-images.githubusercontent.com/29313094/120660527-075d1a00-c44d-11eb-8960-a3a1b9945417.png)
![image](https://user-images.githubusercontent.com/29313094/120660742-3ffcf380-c44d-11eb-8a05-f751a9692250.png)

**Comment by JefferyDaHu** [comment]
I just noticed that I mistakenly closed the issue. I am still not able to get this issue fixed. Thank you for your help.

**Comment by akzeac** [comment]
Hi Jeffery,

sorry, somehow I lost track of this email.
Your error is now "failed to find resource path". This means that the service was found successfully, but the assets weren’t.

I see that you have "/opt/ros/kinetic/share" as the folder where the ROS assets are to be found.
However, this appears to be a Linux path, but the screenshot shows "C:\Users\…" as the location of the file, which is a Windows path.

How is your setup? If the ROS assets are on the Linux system, you need to run a provider on the Linux side, either iviz or the iviz_model_service node.

Otherwise, if you want to stay on Windows, you need to copy the assets there. You can create a folder on Windows (for example, "ROS" in your Windows user folder), copy the turtlebot_description folder into it, and then write the full path of this 'ROS' folder into ros_package_path.

Cheers,
Antonio

**Comment by JefferyDaHu** [comment]
Hi Antonio,

Thank you for your detailed instruction. I followed the instruction as indicated in the figure. iviz app still fails to find the resources. 
![image](https://user-images.githubusercontent.com/29313094/121439960-f03e9080-c954-11eb-9d85-68432a62ab7f.png)
In addition, I tried to run iviz app on Linux along with ROS and it worked fine. I can also manually add the robot in windows. I think those two options work for me now. If I figure out there are any issues with my windows settings, I will update here in the future. Thank you for your contribution in developing such a great tool and making it available.

Thanks,
Jeffery
